[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:launcher]
command=python launcher.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:audiobot]
command=python bot_audio_livekit_fixed.py start
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
